settings:
  checkForUpdates: true
  permissions: true
  useDatabase: false
  folderName: coords
  debug: false
database:
  url: jdbc:mysql://localhost:3306/DATABASE_NAME
  table: coords
  username: user
  password: pass