name: Mapcoords
main: com.guysthatcode.Mapcoords.Mapcoords
version: 1.0.2
description: This plugin can record coordinates and retrieve saved locations.
author: SoleWolf

commands:
   mapcoords:
      description: Lists all available commands
   mc:
      description: Lists all available commands

permissions:
   mapcoords.*:
        description: Gives permission for all mapcoords commands
        children:
            mapcords.add: true
            mapcords.list: true
            mapcords.delete: true
            mapcords.coords: true
            mapcords.saycoords: true

   mapcords.add:
      description: Add location coordinates.
      default: op
   mapcords.list:
      description: Lists all coordinates.
      default: op
   mapcords.delete:
      description: Delete location coordinates
      default: op
   mapcords.coords:
      description: View your own coordinates
      default: true
   mapcords.saycoords:
      description: Say your coordinates
      default: true

   mc.*:
        description: Gives permission for all mapcoords commands
        children:
            mc.add: true
            mc.list: true
            mc.delete: true
            mc.coords: true
            mc.saycoords: true

   mc.add:
      description: Add location coordinates.
      default: op
   mc.list:
      description: Lists all coordinates.
      default: op
   mc.delete:
      description: Delete location coordinates
      default: op
   mc.coords:
      description: View your own coordinates
      default: true
   mc.saycoords:
      description: Say your coordinates
      default: true