name: Mapcoords
main: com.guysthatcode.Mapcoords.Mapcoords
version: 1.0.3
description: This plugin can record coordinates and retrieve saved locations.
author: SoleWolf

commands:
  mapcoords:
    aliases: [mc]
    description: Lists all available commands
    permission: mc
    usage: Type /<command> for all available commands.
permissions:
  mc.*:
    description: Give access to all Mapcoords permissions.
    children:
      mc.add.public: true
      mc.list.public: true
      mc.delete.public: true
      mc.coords: true
      mc.saycoords: true
    default: op
  mc:
    description: Mapcoords base command
    default: true
  mc.add.public:
    description: Add new coordinates to the public list.
    default: false
  mc.list.public:
    description: List all recorded coordinates of the public list.
    default: false
  mc.delete.public:
    description: Delete coordinates from the public list.
    default: false
  mc.coords:
    description: Show a player their current coordinates.
    default: false
  mc.saycoords:
    description: Makes a player say their current coordinates.
    default: false